# Generated by Django 5.0.2 on 2024-08-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='company',
        ),
    ]
