# Generated by Django 5.1.1 on 2024-09-14 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_registrationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationkey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
