# Generated by Django 5.1.1 on 2024-09-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_członekzespolu_konkurs_partner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='granty',
            new_name='konkursy',
        ),
    ]
