# Generated by Django 5.1.1 on 2024-09-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_rename_granty_firma_konkursy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorytet',
            name='konkurs',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='konkursy',
        ),
        migrations.RemoveField(
            model_name='zasadydotacji',
            name='konkurs',
        ),
        migrations.RemoveField(
            model_name='zadanie',
            name='priorytet',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='partnerzy',
        ),
        migrations.AddField(
            model_name='partner',
            name='firma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerzy', to='register.firma'),
        ),
        migrations.DeleteModel(
            name='Terminy',
        ),
        migrations.DeleteModel(
            name='Konkurs',
        ),
        migrations.DeleteModel(
            name='ZasadyDotacji',
        ),
        migrations.DeleteModel(
            name='Priorytet',
        ),
        migrations.DeleteModel(
            name='Zadanie',
        ),
    ]
