# Generated by Django 5.1.1 on 2024-09-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_firma_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_organizacji', models.CharField(max_length=150, verbose_name='Nazwa Organizacji')),
                ('typ_organizacji', models.CharField(max_length=100, verbose_name='Typ Organizacji')),
                ('email', models.EmailField(max_length=100, verbose_name='Adres Email')),
                ('numer_telefonu', models.PositiveIntegerField(null=True, verbose_name='Numer Telefonu')),
                ('adres', models.CharField(max_length=150, null=True, verbose_name='Adres')),
                ('miasto', models.CharField(max_length=50, null=True, verbose_name='Miasto')),
                ('kod_pocztowy', models.CharField(max_length=10, null=True, verbose_name='Kod Pocztowy')),
                ('url', models.URLField(null=True, verbose_name='URL Organizacji')),
                ('rodzaj_zadania', models.CharField(max_length=100, verbose_name='Rodzaj Zadania')),
                ('status_oferty', models.CharField(max_length=50, verbose_name='Status Oferty')),
                ('data_zlozenia', models.DateField(verbose_name='Data Złożenia')),
            ],
        ),
        migrations.CreateModel(
            name='Priorytet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_priorytetu', models.CharField(max_length=100, verbose_name='Nazwa Priorytetu')),
                ('maksymalna_kwota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maksymalna Kwota')),
                ('organizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorytety', to='register.organizacja')),
            ],
        ),
        migrations.CreateModel(
            name='Finansowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota_wnioskowana', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota Wnioskowana')),
                ('rok', models.IntegerField(verbose_name='Rok')),
                ('opis', models.TextField(null=True, verbose_name='Opis Finansowania')),
                ('organizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finansowanie', to='register.organizacja')),
            ],
            options={
                'unique_together': {('organizacja', 'rok')},
            },
        ),
    ]
