# Generated by Django 5.1.1 on 2024-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_organizacja_priorytet_finansowanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacja',
            name='data_zlozenia',
            field=models.DateField(null=True, verbose_name='Data Złożenia'),
        ),
        migrations.AlterField(
            model_name='organizacja',
            name='rodzaj_zadania',
            field=models.CharField(max_length=100, null=True, verbose_name='Rodzaj Zadania'),
        ),
        migrations.AlterField(
            model_name='organizacja',
            name='status_oferty',
            field=models.CharField(max_length=50, null=True, verbose_name='Status Oferty'),
        ),
    ]
