# Generated by Django 5.1.1 on 2024-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_organizacja_data_zlozenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finansowanie',
            name='kwota_wnioskowana',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Kwota Wnioskowana'),
        ),
        migrations.AlterField(
            model_name='finansowanie',
            name='rok',
            field=models.IntegerField(null=True, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='organizacja',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Adres Email'),
        ),
        migrations.AlterField(
            model_name='organizacja',
            name='nazwa_organizacji',
            field=models.CharField(max_length=150, null=True, verbose_name='Nazwa Organizacji'),
        ),
        migrations.AlterField(
            model_name='organizacja',
            name='typ_organizacji',
            field=models.CharField(max_length=100, null=True, verbose_name='Typ Organizacji'),
        ),
        migrations.AlterField(
            model_name='priorytet',
            name='maksymalna_kwota',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Maksymalna Kwota'),
        ),
        migrations.AlterField(
            model_name='priorytet',
            name='nazwa_priorytetu',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa Priorytetu'),
        ),
    ]
