# Generated by Django 5.1.1 on 2024-09-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_finansowanie_kwota_wnioskowana_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finansowanie',
            unique_together=set(),
        ),
    ]
