# Generated by Django 5.1.1 on 2024-09-29 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_alter_finansowanie_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorytet',
            name='organizacja',
        ),
        migrations.RemoveField(
            model_name='priorytet',
            name='maksymalna_kwota',
        ),
        migrations.AddField(
            model_name='priorytet',
            name='opis',
            field=models.TextField(null=True, verbose_name='Opis Priorytetu'),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_grantu', models.CharField(max_length=150, null=True, verbose_name='Nazwa Grantu')),
                ('maksymalna_kwota', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Maksymalna Kwota')),
                ('data_rozpoczecia', models.DateField(null=True, verbose_name='Data Rozpoczęcia')),
                ('data_zakonczenia', models.DateField(null=True, verbose_name='Data Zakończenia')),
                ('opis', models.TextField(null=True, verbose_name='Opis Grantu')),
                ('priorytet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants_s', to='register.priorytet', verbose_name='Priorytet')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_konkursu', models.CharField(max_length=150, null=True, verbose_name='Nazwa Konkursu')),
                ('data_rozpoczecia', models.DateField(null=True, verbose_name='Data Rozpoczęcia')),
                ('data_zakonczenia', models.DateField(null=True, verbose_name='Data Zakończenia')),
                ('opis', models.TextField(null=True, verbose_name='Opis Konkursu')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='Status Konkursu')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='register.grant', verbose_name='Grant')),
            ],
        ),
        migrations.AddField(
            model_name='priorytet',
            name='grants',
            field=models.ManyToManyField(related_name='priorytety', to='register.grant', verbose_name='Grants'),
        ),
        migrations.DeleteModel(
            name='Finansowanie',
        ),
        migrations.DeleteModel(
            name='Organizacja',
        ),
    ]
