# Generated by Django 5.0.2 on 2024-08-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
