# Generated by Django 5.1.1 on 2024-09-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_department_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
